static const char black[]       = "#282a36";
static const char white[]       = "#f8f8f2";
static const char gray2[]       = "#44475a"; // unfocused window border
static const char gray3[]       = "#6272a4";
static const char gray4[]       = "#bd93f9";
static const char blue[]        = "#6272a4";  // focused window border
static const char green[]       = "#50fa7b";
static const char red1[]         = "#ff5555";
static const char red2[]         = "#ff79c6";
static const char orange[]      = "#ffb86c";
static const char yellow[]      = "#f1fa8c";
static const char pink[]        = "#ff79c6";
static const char col_borderbar[]  = "#282a36"; // inner border
